#!/usr/intel/bin/tcsh -f
# EC Standard Login Environment -*- sh -*-
# user .aliases file
# $Source: /usr/cvs/cvsrep/ec_environ-1.0/release/user/aliases,v $
# $Revision: 1.1 $

alias grep 'grep --color=auto'
alias em emacs
alias en 'emacs -nw'
alias e 'emacsclient -n'
alias ef 'emacsclient -c'
alias et 'emacsclient -t'

alias wl 'less -S -# 15' # for use with wide files like trk
alias rp realpath

alias timer '/usr/bin/time --format="TIMER: %C finished in %e seconds"'

alias cdm 'cd $MODEL_ROOT'
alias src-alias 'source $HOME/.aliases'

alias win-xl 'xrandr -s 1920x1200'
alias win-l 'xrandr -s 1920x1080'
alias win-m 'xrandr -s 1536x864'

if ($EC_SITE == fc) then
   alias srcenv 'source /p/hdk/rtl/hdk.rc -cfg shdk73'
else
    alias srcenv 'source /p/hdk/rtl/hdk.rc -cfg shdk74'
endif

alias bld '$GK_CONFIG_DIR/hooks/setup_git_config.pl -c \!:1; nbjob run --target $EC_SITE"_critical" --mail E bman -dut \!:1 -mc \!:2'
alias check 'nbqstat -P $EC_SITE"_critical" --task-name --priority user=$USER'
alias spf 'setenv SPF_ROOT /p/hdk/cad/spf/latest; source $SPF_ROOT/bin/spf_setup_env'
alias run 'simregress -dut \!:1 -model \!:2 -l \!:3 -trex -save -trex- -net'
alias phases 'gzgrep "started\." acerun.log* | grep sla_tb_env | cut -d"@" -f2'
